### ISSUE TITLE
NullReferenceException inside Template10 when opening via OtherSchedule twice

### ISSUE THREAD

**Issue by arthurrump** [arthurrump/Zermelo.App.UWP#31]
Open a ScheduleView for an account via the OtherSchedulesView, then close it with the button added in 39c45fd5, then open a ScheduleView for the same account again. The NavItem in the HamburgerMenu won't get highlighted the second time and NullReferenceExceptions will be thrown inside Template10.Library.

Logs for the first time:
```
Template10 HamburgerMenu.GotFocus Windows.UI.Xaml.Controls.Button name: symbol:Zoek
Template10 NavigationService.Navigate Page: Zermelo.App.UWP.Schedule.ScheduleView, Parameter: 04444, NavigationTransitionInfo: 
Template10 NavigationService.NavigateAsync Page: Zermelo.App.UWP.Schedule.ScheduleView, Parameter: 04444, NavigationTransitionInfo: 
Template10 JsonSerializationService.Serialize Value 04444
Template10 FrameFacade.Navigate 
Template10 FrameFacade.FacadeNavigatingCancelEventHandler 
Template10 JsonSerializationService.Deserialize Value {"Type":"System.String, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","Data":"\"04444\""}
Template10 NavigationService.NavigatingFromAsync Suspending: False
Template10 NavigationService.NavigateFromAsync Suspending: False
Template10 BootStrapper.UpdateShellBackButton 
Template10 FrameFacade.FacadeNavigatedEventHandler 
Template10 JsonSerializationService.Deserialize Value {"Type":"System.String, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","Data":"\"04444\""}
Template10 JsonSerializationService.Deserialize Value {"Type":"System.String, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","Data":"\"04444\""}
Template10 JsonSerializationService.Serialize Value 
Template10 HamburgerMenu.HighlightCorrectButton PageType: Zermelo.App.UWP.Schedule.ScheduleView PageParam: {"Type":"System.String, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","Data":"\"04444\""}
Template10 JsonSerializationService.Deserialize Value {"Type":"System.String, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","Data":"\"04444\""}
Template10 HamburgerMenu.Selected OldValue: IsChecked: True PageType: Zermelo.App.UWP.OtherSchedules.OtherSchedulesView, Parameter:  NewValue: 
Template10 HamburgerMenu.UpdateSelectedAsync OldValue: IsChecked: True PageType: Zermelo.App.UWP.OtherSchedules.OtherSchedulesView, Parameter: , NewValue: 
Template10 HamburgerMenu.NavButtonUnchecked 
Template10 BootStrapper.UpdateShellBackButton 

BackStack:
    ScheduleView ({"Type":"System.String, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","Data":"\"~me\""})
    OtherSchedulesView ()
Current: ScheduleView (04444)
ForwardStack:

Template10 HamburgerMenu.NavButton_Loaded 
Template10 HamburgerMenu.HighlightCorrectButton PageType: Zermelo.App.UWP.Schedule.ScheduleView PageParam: 04444
Template10 HamburgerMenu.Selected OldValue:  NewValue: IsChecked: False PageType: Zermelo.App.UWP.Schedule.ScheduleView, Parameter: 04444
Template10 HamburgerMenu.UpdateSelectedAsync OldValue: , NewValue: IsChecked: False PageType: Zermelo.App.UWP.Schedule.ScheduleView, Parameter: 04444
Template10 NavigationService.NavigateAsync Page: Zermelo.App.UWP.Schedule.ScheduleView, Parameter: 04444, NavigationTransitionInfo: 
Template10 HamburgerMenu.NavButtonChecked 
Template10 HamburgerMenu.GotFocus Windows.UI.Xaml.Controls.Button name:HamburgerButton symbol:Windows.UI.Xaml.Controls.FontIcon
Template10 NavigationService.NavigateToAsync Mode: New, Parameter: 04444 FrameContent: Zermelo.App.UWP.Schedule.ScheduleView
```

Logs for the second time:
```
Template10 HamburgerMenu.GotFocus Windows.UI.Xaml.Controls.Button name: symbol:Zoek
Template10 NavigationService.Navigate Page: Zermelo.App.UWP.Schedule.ScheduleView, Parameter: 04444, NavigationTransitionInfo: 
Template10 NavigationService.NavigateAsync Page: Zermelo.App.UWP.Schedule.ScheduleView, Parameter: 04444, NavigationTransitionInfo: 
Template10 JsonSerializationService.Serialize Value 04444
Template10 FrameFacade.Navigate 
Template10 FrameFacade.FacadeNavigatingCancelEventHandler 
Template10 JsonSerializationService.Deserialize Value {"Type":"System.String, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","Data":"\"04444\""}
Template10 NavigationService.NavigatingFromAsync Suspending: False
Template10 NavigationService.NavigateFromAsync Suspending: False
Template10 BootStrapper.UpdateShellBackButton 
Template10 FrameFacade.FacadeNavigatedEventHandler 
Template10 JsonSerializationService.Deserialize Value {"Type":"System.String, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","Data":"\"04444\""}
Template10 JsonSerializationService.Deserialize Value {"Type":"System.String, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","Data":"\"04444\""}
Template10 JsonSerializationService.Serialize Value 
Template10 HamburgerMenu.HighlightCorrectButton PageType: Zermelo.App.UWP.Schedule.ScheduleView PageParam: {"Type":"System.String, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","Data":"\"04444\""}
Template10 JsonSerializationService.Deserialize Value {"Type":"System.String, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","Data":"\"04444\""}
Template10 HamburgerMenu.Selected OldValue: IsChecked: True PageType: Zermelo.App.UWP.OtherSchedules.OtherSchedulesView, Parameter:  NewValue: IsChecked: False PageType: Zermelo.App.UWP.Schedule.ScheduleView, Parameter: 04444
Template10 HamburgerMenu.UpdateSelectedAsync OldValue: IsChecked: True PageType: Zermelo.App.UWP.OtherSchedules.OtherSchedulesView, Parameter: , NewValue: IsChecked: False PageType: Zermelo.App.UWP.Schedule.ScheduleView, Parameter: 04444
Template10 HamburgerMenu.NavButtonUnchecked 
Template10 NavigationService.NavigateAsync Page: Zermelo.App.UWP.Schedule.ScheduleView, Parameter: 04444, NavigationTransitionInfo: 
Template10 HamburgerMenu.NavButtonChecked 
Exception thrown: 'System.NullReferenceException' in Template10Library.dll
Exception thrown: 'System.IO.FileLoadException' in System.Private.CoreLib.ni.dll
Exception thrown: 'System.IO.FileLoadException' in System.Private.CoreLib.ni.dll
Exception thrown: 'System.NullReferenceException' in Template10Library.dll
Exception thrown: 'System.NullReferenceException' in System.Private.CoreLib.ni.dll
Template10 HamburgerMenu.SelectedPropertyChanged Catch Ex.Message: Object reference not set to an instance of an object.
Template10 BootStrapper.UpdateShellBackButton 

BackStack:
    ScheduleView ({"Type":"System.String, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","Data":"\"~me\""})
    OtherSchedulesView ()
Current: ScheduleView (04444)
ForwardStack:

Template10 HamburgerMenu.NavButton_Loaded 
Template10 HamburgerMenu.HighlightCorrectButton PageType: Zermelo.App.UWP.Schedule.ScheduleView PageParam: 04444
Template10 HamburgerMenu.GotFocus Windows.UI.Xaml.Controls.Button name:HamburgerButton symbol:Windows.UI.Xaml.Controls.FontIcon
Template10 NavigationService.NavigateToAsync Mode: New, Parameter: 04444 FrameContent: Zermelo.App.UWP.Schedule.ScheduleView
```

**Comment by arthurrump** [comment]
StackTrace:
```
   at Template10.Controls.HamburgerMenu.NavButtonChecked(Object sender, RoutedEventArgs e)
   at Windows.UI.Xaml.DependencyObject.SetValue(DependencyProperty dp, Object value)
   at Template10.Controls.HamburgerButtonInfo.set_IsChecked(Nullable`1 value)
   at Template10.Controls.HamburgerMenu.<UpdateSelectedAsync>d__302.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Template10.Controls.HamburgerMenu.<InternalSelectedChanged>d__209.MoveNext()
```

**Comment by arthurrump** [comment]
Code from Template10 (HamburgerMenu.xaml.cs):
```
        private void NavButtonChecked(object sender, RoutedEventArgs e)
        {
            DebugWrite();

            var button = new InfoElement(sender);
            if (button.HamburgerButtonInfo.ButtonType == HamburgerButtonInfo.ButtonTypes.Toggle)
            {
                button.HamburgerButtonInfo.IsChecked = (button.HamburgerButtonInfo.ButtonType == HamburgerButtonInfo.ButtonTypes.Toggle);
                if (button.HamburgerButtonInfo.IsChecked ?? true) Selected = button.HamburgerButtonInfo;
                if (button.HamburgerButtonInfo.IsChecked ?? true) button.HamburgerButtonInfo.RaiseChecked(e);
                button.FrameworkElement.IsHitTestVisible = !button.HamburgerButtonInfo.IsChecked ?? false;
            }
        }
```

It throws at the if-statement, because button.HamburgerButtonInfo is null. The HamburgerButtonInfo is set as sender.DataContext, which is null.

**Comment by arthurrump** [comment]
When automatic navigation is disabled and the button only gets added in OtherScheduleViewModel, and the added navbutton gets clicked, the first time NavButtonChecked gets called once, all following times it gets called thrice, with the middle call without the DataContext.

**Comment by arthurrump** [comment]
🎉 Found the problem: removing the navbutton from the HamburgerMenu doesn't remove it from the LoadedNavButtons list. When I remove it from there manually, everything works fine.
